#pragma once

#define TAPPING_TERM 150
#define COMBO_TERM 50
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1000
#define CHARYBDIS_DRAGSCROLL_ENABLE
#define CHARYBDIS_DRAGSCROLL_DIVISOR_H 192
#define CHARYBDIS_DRAGSCROLL_DIVISOR_V 192
#define CHARYBDIS_DRAGSCROLL_REVERSE_SCROLL_Y
#define CHARYBDIS_DRAGSCROLL_REVERSE_SCROLL_X
